package mygrocerylist.listandshop;

import android.app.Activity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.View;
import android.view.WindowManager;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ListView;

import java.util.ArrayList;


public class listSearch extends AppCompatActivity {

    private ArrayAdapter adapter;
    Intent baboosh; //to change activities
    Intent ganesh;
    //Intent darambar;
    ArrayList<String> myList;
    ArrayList<Integer> theImage;
    ListView list;
    Integer index;
    Integer top; ////both of these values to save position of list
    ArrayList<Items> items = null;
    ArrayList<String> items2 = null;
    Button button;


   // LinkedHashMap<String, Integer> theList;



    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        SharedPreferences sp = getSharedPreferences("your_prefs", Activity.MODE_PRIVATE);
        index = sp.getInt("index", 0);
        top = sp.getInt("top", 0);

        getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN); //hide keyboard
        //prevent keyboard from moving view

        setContentView(mygrocerylist.listandshop.R.layout.list_search); //sets list search layout as view
        myList = MainActivity.getArrayList("Names", this); //loads arraylist
        theImage = MainActivity.getArrayListInt("Image", this);

        items = new ArrayList<>();
        items2 = new ArrayList<>();
        items2 = MainActivity.getArrayList("Custom", this);
        items = populateData(items);




        baboosh = new Intent(this, MainActivity.class); //loads mainactivity
        ganesh = new Intent(this, AddNewItem.class);

        final ListView list = findViewById(mygrocerylist.listandshop.R.id.theListView);  //the list
        EditText theFilter = findViewById(mygrocerylist.listandshop.R.id.filter); //the edittext


        //add new item
        button = findViewById(R.id.addnew);
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                startActivity(ganesh);
            }
        });

        adapter = new ListViewClass(getApplicationContext(), items);
        list.setAdapter(adapter);

        list.setSelectionFromTop(index, top); //remember last position

        list.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> adapter, View v, int position,
                                    long arg3) {
                Items clickedItem = (Items) adapter.getItemAtPosition(position);

                //save list position
                index = list.getFirstVisiblePosition();
                v = list.getChildAt(0);
                top = (v == null) ? 0 : (v.getTop() - list.getPaddingTop());
                SharedPreferences sp = getSharedPreferences("your_prefs", Activity.MODE_PRIVATE);
                SharedPreferences.Editor editor = sp.edit();
                editor.putInt("index", index);
                editor.putInt("top", top);
                //editor.commit();


                myList.add(clickedItem.getItemName());//gets the string part of the object and puts it into an arraylist
                theImage.add(clickedItem.getNoOfArray()); //ditto but int
                MainActivity.saveArrayList(myList, "Names", getApplicationContext());
                MainActivity.saveArrayListInt(theImage, "Image", getApplicationContext());
                editor.apply();//get the lists from sharedprefs
                startActivity(baboosh);


                // }
            }
        });
        //https://stackoverflow.com/questions/24769257/custom-listview-adapter-with-filter-android

        theFilter.addTextChangedListener(new TextWatcher() {

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {

                adapter.getFilter().filter(s.toString());
                adapter.notifyDataSetChanged();

            }

            @Override
            public void beforeTextChanged(CharSequence s, int start, int count,
                                          int after) {

            }

            @Override
            public void afterTextChanged(Editable s) {


            }
        });
    }


/*    public HashMap<String, Integer> getTheList()
    {
        return theList;
    }*/

    private ArrayList<Items> populateData(ArrayList<Items> items){

    items.add(new Items("Almond butter", 1, 1));
    items.add(new Items("Almond milk", 2, 1));
    items.add(new Items("Almonds", 3, 1));
    //items.add(new Items("Almonds", 4, 1));
    items.add(new Items("Aluminum foil", 5, 1));
    items.add(new Items("Amaranth", 6, 1));
    items.add(new Items("Anise", 7, 1));
    items.add(new Items("Antacid", 8, 1));
    items.add(new Items("Antibiotic", 9, 1));
    items.add(new Items("Deodorant", 10, 1));
    items.add(new Items("Apple cider vinegar", 11, 1));
    items.add(new Items("Apple Juice", 12, 1));
    items.add(new Items("Apple vinegar", 13, 1));
    items.add(new Items("Apples", 14, 1));
    items.add(new Items("Applesauce", 15, 1));
    items.add(new Items("Apricots", 16, 1));
    items.add(new Items("Artichokes", 17, 1));
    items.add(new Items("Arugula", 18, 1));
    items.add(new Items("Asparagus", 19, 1));
    items.add(new Items("Aspirin", 20, 1));
    //items.add(new Items("Automotive Parts", 21, 1));
    items.add(new Items("Avocado", 22, 1));
    items.add(new Items("Baby Carrots", 23, 1));
    items.add(new Items("Baby food", 24, 1));
    items.add(new Items("Baby wash", 25, 1));
    items.add(new Items("Bagels", 26, 1));
    items.add(new Items("Baguette", 27, 1));
    items.add(new Items("Baked beans", 28, 1));
    items.add(new Items("Baking powder", 29, 1));
    items.add(new Items("Baking Soda", 30, 1));
    items.add(new Items("Balsamic vinegar", 31, 1));
    items.add(new Items("Bamboo shoots", 32, 1));
    items.add(new Items("Bananas", 33, 1));
    items.add(new Items("Band-aids", 34, 1));
    items.add(new Items("Barley", 35, 1));
    items.add(new Items("Basil", 36, 1));
    items.add(new Items("Bathroom cleaner", 37, 1));
    items.add(new Items("Batteries", 38, 1));
    items.add(new Items("Bay leaf", 39, 1));
    items.add(new Items("BBQ Sauce", 40, 1));
    items.add(new Items("Beef", 41, 1));
    items.add(new Items("Beets", 42, 1));
    items.add(new Items("Bell peppers", 43, 1));
    items.add(new Items("Berries", 44, 1));
    items.add(new Items("Black beans", 45, 1));
    items.add(new Items("Black pepper", 46, 1));
    items.add(new Items("Blackberries", 47, 1));
    items.add(new Items("Black-eyed peas", 48, 1));
    items.add(new Items("Bleach", 49, 1));
    items.add(new Items("Bleu cheese", 50, 1));
    items.add(new Items("Blood oranges", 51, 1));
    items.add(new Items("Blueberries", 52, 1));
    items.add(new Items("Bok choy", 53, 1));
    items.add(new Items("Bouillon cubes", 54, 1));
    items.add(new Items("Brazil nuts", 55, 1));
    items.add(new Items("Bread", 56, 1));
    items.add(new Items("Bread crumbs", 57, 1));
    items.add(new Items("Breakfast food", 58, 1));
    items.add(new Items("Broccoli", 59, 1));
    //items.add(new Items("Broccoli", 60, 1));
    items.add(new Items("Brown rice", 61, 1));
    items.add(new Items("Brownies", 62, 1));
    items.add(new Items("Brussels sprouts", 63, 1));
    items.add(new Items("Buckwheat", 64, 1));
    items.add(new Items("Bulgar", 65, 1));
    items.add(new Items("Buns / Rolls", 66, 1));
    items.add(new Items("Burger night", 67, 1));
    items.add(new Items("Burritos", 68, 1));
    items.add(new Items("Butter", 69, 1));
    items.add(new Items("Cabbage", 70, 1));
    items.add(new Items("Cake", 71, 1));
    items.add(new Items("Cake icing", 72, 1));
    items.add(new Items("Cake Mix", 73, 1));
    items.add(new Items("Candy", 74, 1));
    items.add(new Items("Cantaloupe", 75, 1));
    items.add(new Items("Carrots", 76, 1));
    items.add(new Items("Cashews", 77, 1));
    //items.add(new Items("Cashews", 78, 1));
    items.add(new Items("Cassava", 79, 1));
    items.add(new Items("Cat food", 80, 1));
    items.add(new Items("Cat litter", 81, 1));
    items.add(new Items("Cat Treats", 82, 1));
    items.add(new Items("Catfish", 83, 1));
    items.add(new Items("Cauliflower", 84, 1));
    items.add(new Items("Cayenne pepper", 85, 1));
    items.add(new Items("Celery", 86, 1));
    items.add(new Items("Celery seed", 87, 1));
    items.add(new Items("Cereal", 88, 1));
    items.add(new Items("Cereal bars", 89, 1));
    items.add(new Items("Chai", 90, 1));
    items.add(new Items("Charcoal", 91, 1));
    items.add(new Items("Propane", 92, 1));
    items.add(new Items("Chard", 93, 1));
    //items.add(new Items("Cheddar", 94, 1));
    items.add(new Items("Cheddar cheese", 95, 1));
    items.add(new Items("Cherries", 96, 1));
    items.add(new Items("Chestnuts", 97, 1));
    items.add(new Items("Chicken", 98, 1));
    items.add(new Items("Chickpeas", 99, 1));
    items.add(new Items("Chili Peppers", 100, 1));
    items.add(new Items("Chocolate", 101, 1));
    //items.add(new Items("Chili Pepper", 102, 1));
    items.add(new Items("Chili powder", 103, 1));
    items.add(new Items("Chip Dip", 104, 1));
    items.add(new Items("Chives", 105, 1));
    items.add(new Items("Cocoa", 106, 1));
    items.add(new Items("Cilantro", 107, 1));
    items.add(new Items("Cinnamon", 108, 1));
    items.add(new Items("Cling Wrap", 109, 1));
    items.add(new Items("Clove", 110, 1));
    items.add(new Items("Club soda / Tonic", 111, 1));
    items.add(new Items("Coca Cola", 112, 1));
    items.add(new Items("Coconuts", 113, 1));
    items.add(new Items("Coffee", 114, 1));
    items.add(new Items("Coffee Filters", 115, 1));
    items.add(new Items("Cold Medicine", 116, 1));
    items.add(new Items("Collard greens", 117, 1));
    items.add(new Items("Compress", 118, 1));
    items.add(new Items("Conditioner", 119, 1));
    items.add(new Items("Cookies", 120, 1));
    //items.add(new Items("Soy milk", 121, 1));
    items.add(new Items("Coriander", 122, 1));
    items.add(new Items("Corn", 123, 1));
    items.add(new Items("Corn chips", 124, 1));
    items.add(new Items("Cornmeal", 125, 1));
    items.add(new Items("Cosmetics", 126, 1));
    items.add(new Items("Cottage cheese", 127, 1));
    items.add(new Items("Cotton Balls", 128, 1));
    items.add(new Items("Couscous", 129, 1));
    items.add(new Items("Crab", 130, 1));
    items.add(new Items("Crackers", 131, 1));
    items.add(new Items("Cranberries", 132, 1));
    items.add(new Items("Cream", 133, 1));
    items.add(new Items("Cream cheese", 134, 1));
    items.add(new Items("Crisp head lettuce", 135, 1));
    items.add(new Items("Croissants", 136, 1));
    items.add(new Items("Cucumbers", 137, 1));
    items.add(new Items("Cumin", 138, 1));
    //items.add(new Items("Cups", 139, 1));
    items.add(new Items("Cutlery", 140, 1));
    items.add(new Items("Daikon", 141, 1));
    items.add(new Items("Dates", 142, 1));
    items.add(new Items("Detergent", 143, 1));
    items.add(new Items("Diapers", 144, 1));
    items.add(new Items("Dill", 145, 1));
    items.add(new Items("Dishwasher soap", 146, 1));
    items.add(new Items("Dog food", 147, 1));
    items.add(new Items("Dog Treats", 148, 1));
    items.add(new Items("Donuts", 149, 1));
    items.add(new Items("Dried fruit", 150, 1));
    items.add(new Items("Earl Grey Tea", 151, 1));
    items.add(new Items("Edamame", 152, 1));
    //items.add(new Items("Egg substitute", 153, 1));
    items.add(new Items("Egg whites", 154, 1));
    items.add(new Items("Eggplant", 155, 1));
    items.add(new Items("Eggs", 156, 1));
    items.add(new Items("Electrolyte water", 157, 1));
    items.add(new Items("Endive", 158, 1));
    items.add(new Items("English Muffins", 159, 1));
    items.add(new Items("Facial cleanser", 160, 1));
    items.add(new Items("Tissue", 161, 1));
    //items.add(new Items("Fake eggs", 162, 1));
    items.add(new Items("Fanta Lemon", 163, 1));
    items.add(new Items("Fanta Orange", 164, 1));
    items.add(new Items("Fava beans", 165, 1));
    items.add(new Items("Feminine products", 166, 1));
    items.add(new Items("Fennel", 167, 1));
    items.add(new Items("Feta cheese", 168, 1));
    items.add(new Items("Figs", 169, 1));
    items.add(new Items("Fish Sticks", 170, 1));
    items.add(new Items("Flax", 171, 1));
    //items.add(new Items("Flea treatment", 172, 1));
    items.add(new Items("Floss", 173, 1));
    items.add(new Items("Flour", 174, 1));
    items.add(new Items("Flowers", 175, 1));
    //items.add(new Items("Formula", 176, 1));
    items.add(new Items("Free-range eggs", 177, 1));
    items.add(new Items("Freezer bags", 178, 1));
    items.add(new Items("French Fries", 179, 1));
    items.add(new Items("Fresh bread", 180, 1));
    items.add(new Items("Frozen Breakfast", 181, 1));
    items.add(new Items("Frozen Vegetables", 182, 1));
    items.add(new Items("Fruit", 183, 1));
    items.add(new Items("Fruit juice", 184, 1));
    items.add(new Items("Gala Apples", 185, 1));
    items.add(new Items("Garbage bags", 186, 1));
    items.add(new Items("Garlic", 187, 1));
    items.add(new Items("Ginger", 188, 1));
    //items.add(new Items("Glasses", 189, 1));
    items.add(new Items("Goat cheese", 190, 1));
    items.add(new Items("Golden Apples", 191, 1));
    items.add(new Items("Granola bars", 192, 1));
    items.add(new Items("Granola Mix", 193, 1));
    items.add(new Items("Grapefruit", 194, 1));
    items.add(new Items("Grapes", 195, 1));
    items.add(new Items("Gravy", 196, 1));
    items.add(new Items("Green bean", 197, 1));
    items.add(new Items("Green bell peppers", 198, 1));
    items.add(new Items("Greens", 199, 1));
    items.add(new Items("Greeting cards", 200, 1));
    items.add(new Items("Ground beef", 201, 1));
    items.add(new Items("Ground Turkey", 202, 1));
    items.add(new Items("Guava", 203, 1));
    items.add(new Items("Gum", 204, 1));
    items.add(new Items("Habanero chili", 205, 1));
    items.add(new Items("Hair Gel", 206, 1));
    items.add(new Items("Half & half", 207, 1));
    items.add(new Items("Honey", 208, 1));
    items.add(new Items("Honeydew / Muskmelon", 209, 1));
    items.add(new Items("Hot dogs", 210, 1));
    items.add(new Items("Hot peppers", 211, 1));
    items.add(new Items("Hot Sauce", 212, 1));
    items.add(new Items("Hummus", 213, 1));
    items.add(new Items("Ice Cream", 214, 1));
    items.add(new Items("Insect repellent", 215, 1));
    items.add(new Items("Instant potatoes", 216, 1));
    items.add(new Items("Jalapeños", 217, 1));
    items.add(new Items("Jam", 218, 1));
    //items.add(new Items("Jam", 219, 1));
    items.add(new Items("Jelly", 220, 1));
    items.add(new Items("Jicama", 221, 1));
    items.add(new Items("Juice", 222, 1));
    items.add(new Items("Juice Concentrate", 223, 1));
    items.add(new Items("Kale", 224, 1));
    items.add(new Items("Ketchup", 225, 1));
    items.add(new Items("Kidney beans", 226, 1));
    //items.add(new Items("Kiwifruits", 227, 1));
    items.add(new Items("Kiwi", 228, 1));
    items.add(new Items("Kohlrabi", 229, 1));
    items.add(new Items("Kombucha", 230, 1));
    items.add(new Items("Kumquats", 231, 1));
    items.add(new Items("Lavender", 232, 1));
    items.add(new Items("Leeks", 233, 1));
    items.add(new Items("Lemon Juice", 234, 1));
    items.add(new Items("Lemongrass", 235, 1));
    items.add(new Items("Lemons", 236, 1));
    items.add(new Items("Lentils", 237, 1));
    items.add(new Items("Lettuce", 238, 1));
    items.add(new Items("Lima beans", 239, 1));
    items.add(new Items("Lime juice", 240, 1));
    items.add(new Items("Limes", 241, 1));
    //items.add(new Items("Limes", 242, 1));
    items.add(new Items("Lip balm", 243, 1));
    items.add(new Items("Lobster", 244, 1));
    items.add(new Items("Lotion", 245, 1));
    items.add(new Items("Lotus", 246, 1));
    items.add(new Items("Lunchmeat", 247, 1));
    items.add(new Items("Lychee", 248, 1));
    items.add(new Items("Mac & Cheese", 249, 1));
    items.add(new Items("Macadamia", 250, 1));
    items.add(new Items("Makeup", 251, 1));
    items.add(new Items("Mandarin oranges", 252, 1));
    items.add(new Items("Mango", 253, 1));
    items.add(new Items("Mangosteen", 254, 1));
    items.add(new Items("Margarine", 255, 1));
    items.add(new Items("Marjoram", 256, 1));
    items.add(new Items("Mashed Potatoes", 257, 1));
    items.add(new Items("Mayonnaise", 258, 1));
    items.add(new Items("Melon", 259, 1));
    items.add(new Items("Milk", 260, 1));
    items.add(new Items("Milk powder", 261, 1));
    items.add(new Items("Millet", 262, 1));
    items.add(new Items("Mint", 263, 1));
    items.add(new Items("Moisturizing lotion", 264, 1));
    items.add(new Items("Mop head", 265, 1));
    items.add(new Items("Mouthwash", 266, 1));
    items.add(new Items("Mozzarella", 267, 1));
    //items.add(new Items("Mozzarella cheese", 268, 1));
    items.add(new Items("Mung beans", 269, 1));
    items.add(new Items("Mushrooms", 270, 1));
    items.add(new Items("Mussels", 271, 1));
    items.add(new Items("Mustard", 272, 1));
    //items.add(new Items("Mustard", 273, 1));
    items.add(new Items("Napkins", 274, 1));
    items.add(new Items("Nappies", 275, 1));
    items.add(new Items("Navy beans", 276, 1));
    items.add(new Items("Nectarines", 277, 1));
    items.add(new Items("Non-stick spray", 278, 1));
    items.add(new Items("Nopales", 279, 1));
    items.add(new Items("Nutmeg", 280, 1));
    items.add(new Items("Nutritional yeast", 281, 1));
    items.add(new Items("Nuts", 282, 1));
    items.add(new Items("Oatmeal", 283, 1));
    items.add(new Items("Okra", 284, 1));
    items.add(new Items("Olive Oil", 285, 1));
    items.add(new Items("Olives", 286, 1));
    items.add(new Items("Onions", 287, 1));
    items.add(new Items("Orange Juice", 288, 1));
    //items.add(new Items("Orange Juice", 289, 1));
    items.add(new Items("Oranges", 290, 1));
    items.add(new Items("Oregano", 291, 1));
    items.add(new Items("Oysters", 292, 1));
    items.add(new Items("Pain reliever", 293, 1));
    items.add(new Items("Pancakes", 294, 1));
    items.add(new Items("Papaya", 295, 1));
    items.add(new Items("Paper towels", 296, 1));
    items.add(new Items("Paprika", 297, 1));
    items.add(new Items("Parsley", 298, 1));
    items.add(new Items("Parmesan cheese", 299, 1));
    //items.add(new Items("Parsley", 300, 1));
    items.add(new Items("Parsnips", 301, 1));
    items.add(new Items("Passionfruit", 302, 1));
    items.add(new Items("Pasta", 303, 1));
    items.add(new Items("Pasta Sauce", 304, 1));
    items.add(new Items("Pastries", 305, 1));
    items.add(new Items("Peach Juice", 306, 1));
    items.add(new Items("Peaches", 307, 1));
    items.add(new Items("Peanut butter", 308, 1));
    items.add(new Items("Peanuts", 309, 1));
    items.add(new Items("Pears", 310, 1));
    items.add(new Items("Peas", 311, 1));
    items.add(new Items("Pecans", 312, 1));
    items.add(new Items("Pens / Pencils", 313, 1));
    items.add(new Items("Peppermint", 314, 1));
    items.add(new Items("Peppers", 315, 1));
    items.add(new Items("Pet shampoo", 316, 1));
    items.add(new Items("Pickles", 317, 1));
    items.add(new Items("Pie!", 318, 1));
    items.add(new Items("Pine nuts", 319, 1));
    items.add(new Items("Pineapple", 320, 1));
    items.add(new Items("Pineapple Juice", 321, 1));
    items.add(new Items("Pinto beans", 322, 1));
    items.add(new Items("Pistachios", 323, 1));
    items.add(new Items("Pita bread", 324, 1));
    //items.add(new Items("Pitas", 325, 1));
    items.add(new Items("Pizza", 326, 1));
    //items.add(new Items("Pizza", 327, 1));
    items.add(new Items("Pizza Rolls", 328, 1));
    items.add(new Items("Plantains", 329, 1));
    items.add(new Items("Plastic wrap", 330, 1));
    //items.add(new Items("Plates", 331, 1));
    items.add(new Items("Plums", 332, 1));
    items.add(new Items("Pomegranates", 333, 1));
    items.add(new Items("Popcorn", 334, 1));
    items.add(new Items("Poppy seed", 335, 1));
    items.add(new Items("Popsicles", 336, 1));
    items.add(new Items("Postage stamps", 337, 1));
    items.add(new Items("Potato chips", 338, 1));
    items.add(new Items("Potatoes", 339, 1));
    items.add(new Items("Prepared meals", 340, 1));
    items.add(new Items("Prescription pick-up", 341, 1));
    items.add(new Items("Preserves", 342, 1));
    items.add(new Items("Pretzels", 343, 1));
    items.add(new Items("Printer paper", 344, 1));
    items.add(new Items("Provolone cheese", 345, 1));
    items.add(new Items("Prunes", 346, 1));
    items.add(new Items("Puff pastry", 347, 1));
    items.add(new Items("Pumpkin", 348, 1));
    items.add(new Items("Quail Eggs", 349, 1));
    items.add(new Items("Quince", 350, 1));
    items.add(new Items("Quinoa", 351, 1));
    items.add(new Items("Radicchio", 352, 1));
    items.add(new Items("Radishes", 353, 1));
    items.add(new Items("Raisins", 354, 1));
    items.add(new Items("Ranch", 355, 1));
    items.add(new Items("Random impulse buy!", 356, 1));
    items.add(new Items("Raspberries", 357, 1));
    //items.add(new Items("Raspberry", 358, 1));
    //items.add(new Items("Razors", 359, 1));
    items.add(new Items("Ready-bake breads", 360, 1));
    items.add(new Items("Red beans", 361, 1));
    items.add(new Items("Red bell peppers", 362, 1));
    items.add(new Items("Red Cabbages", 363, 1));
    items.add(new Items("Red onions", 364, 1));
    items.add(new Items("Red Pepper", 365, 1));
    //items.add(new Items("Red pepper", 366, 1));
    items.add(new Items("Red wine vinegar", 367, 1));
    items.add(new Items("Relish", 368, 1));
    items.add(new Items("Rhubarb", 369, 1));
    items.add(new Items("Rice", 370, 1));
    //items.add(new Items("Rice", 371, 1));
    items.add(new Items("Rice milk", 372, 1));
    items.add(new Items("Rice vinegar", 373, 1));
    //items.add(new Items("Ricotta", 374, 1));
    items.add(new Items("Ricotta cheese", 375, 1));
    items.add(new Items("Romaine lettuce", 376, 1));
    items.add(new Items("Rosemary", 377, 1));
    items.add(new Items("Saffron", 378, 1));
    items.add(new Items("Salad Dressing", 379, 1));
    items.add(new Items("Salmon", 380, 1));
    items.add(new Items("Salsa", 381, 1));
    items.add(new Items("Salt", 382, 1));
    //items.add(new Items("Sandwich bags", 383, 1));
    items.add(new Items("Sandwich cheese slices", 384, 1));
    //items.add(new Items("Sandwich slices", 385, 1));
    items.add(new Items("Seeds", 386, 1));
    items.add(new Items("Sesame oil", 387, 1));
    items.add(new Items("Shallots", 388, 1));
    //items.add(new Items("Shampoo", 389, 1));
    //items.add(new Items("Shaving cream", 390, 1));
    items.add(new Items("Shortening", 391, 1));
    items.add(new Items("Shrimp", 392, 1));
    items.add(new Items("Sliced bread", 393, 1));
    //items.add(new Items("Sliced bread", 394, 1));
    //items.add(new Items("Sliced bread", 395, 1));
    items.add(new Items("Soap", 396, 1));
    items.add(new Items("Soda pop", 397, 1));
    items.add(new Items("Sorbet", 398, 1));
    //items.add(new Items("Sorbet", 399, 1));
    items.add(new Items("Sorghum", 400, 1));
    items.add(new Items("Soups", 401, 1));
    items.add(new Items("Sour cream", 402, 1));
    items.add(new Items("Soy butter", 403, 1));
    //items.add(new Items("Soy I.C.", 404, 1));
    items.add(new Items("Soy milk", 405, 1));
    items.add(new Items("Soy Sauce", 406, 1));
    items.add(new Items("Soy yogurt", 407, 1));
    items.add(new Items("Spaghetti", 408, 1));
    //items.add(new Items("Spice mix", 409, 1));
    items.add(new Items("Spices", 410, 1));
    items.add(new Items("Spinach", 411, 1));
    items.add(new Items("Split peas", 412, 1));
    //items.add(new Items("Sponges / Scrubbers", 413, 1));
    items.add(new Items("Sports drink", 414, 1));
    //items.add(new Items("Sprite", 415, 1));
    items.add(new Items("Sprouts", 416, 1));
    items.add(new Items("Squash", 417, 1));
    items.add(new Items("Steak", 418, 1));
    items.add(new Items("Steak Sauce", 419, 1));
    items.add(new Items("Stevia", 420, 1));
    items.add(new Items("Stir fry sauce", 421, 1));
    items.add(new Items("Strawberries", 422, 1));
    items.add(new Items("Sugar", 423, 1));
    //items.add(new Items("Sugar substitute", 424, 1));
    //items.add(new Items("Sunblock", 425, 1));
    items.add(new Items("Sunflower", 426, 1));
    items.add(new Items("Supplements", 427, 1));
    items.add(new Items("Sweet corn", 428, 1));
    items.add(new Items("Sweet potatoes", 429, 1));
    items.add(new Items("Swiss cheese", 430, 1));
    //items.add(new Items("Swiss cheese", 431, 1));
    items.add(new Items("Syrup", 432, 1));
    items.add(new Items("Tacos", 433, 1));
    items.add(new Items("Tahini", 434, 1));
    items.add(new Items("Take-out food", 435, 1));
    items.add(new Items("Tangerines", 436, 1));
    items.add(new Items("Taro", 437, 1));
    items.add(new Items("Tater tots", 438, 1));
    items.add(new Items("Tea", 439, 1));
    //items.add(new Items("Tempeh", 440, 1));
    items.add(new Items("Tilapia", 441, 1));
    items.add(new Items("Tinned meats", 442, 1));
    items.add(new Items("Tofu", 443, 1));
    ///items.add(new Items("Toilet paper", 444, 1));
    items.add(new Items("Tomatillo", 445, 1));
    items.add(new Items("Tomato sauce", 446, 1));
    items.add(new Items("Tomatoes", 447, 1));
    //items.add(new Items("Toothpaste", 448, 1));
    items.add(new Items("Tortillas", 449, 1));
    //items.add(new Items("Tortillas", 450, 1));
    items.add(new Items("Trail mix", 451, 1));
    items.add(new Items("Tuna", 452, 1));
    //items.add(new Items("Tuna / Chicken", 453, 1));
    items.add(new Items("Turkey", 454, 1));
    //items.add(new Items("Turkey", 455, 1));
    items.add(new Items("Turmeric", 456, 1));
    items.add(new Items("Turnips", 457, 1));
    //items.add(new Items("Turnips / Parsnips", 458, 1));
    items.add(new Items("TV Dinner", 459, 1));
    //items.add(new Items("TV dinners", 460, 1));
    //items.add(new Items("TVP", 461, 1));
    //items.add(new Items("Vacuum bags", 462, 1));
    items.add(new Items("Vanilla extract", 463, 1));
    //items.add(new Items("Veg. Worcestershire", 464, 1));
    items.add(new Items("Vegetable oil", 465, 1));
    items.add(new Items("Vegetable shortening", 466, 1));
    items.add(new Items("Vegetables", 467, 1));
    //items.add(new Items("Veggie breakfasts", 468, 1));
   // items.add(new Items("Veggie Burger", 469, 1));
    //items.add(new Items("Veggie burgers", 470, 1));
    //items.add(new Items("Veggie burritos", 471, 1));
    //items.add(new Items("Veggie dogs", 472, 1));
    //items.add(new Items("Veggie pizzas", 473, 1));
    items.add(new Items("Veggies", 474, 1));
    items.add(new Items("Vinegar", 475, 1));
    items.add(new Items("Vitamins", 476, 1));
    items.add(new Items("Waffles", 477, 1));
    items.add(new Items("Walnut", 478, 1));
    //items.add(new Items("Walnuts", 479, 1));
    items.add(new Items("Water Bottles", 480, 1));
    items.add(new Items("Water chestnuts", 481, 1));
    items.add(new Items("Watercress", 482, 1));
    items.add(new Items("Watermelon", 483, 1));
    //items.add(new Items("Wax paper", 484, 1));
    items.add(new Items("Wheat gluten", 485, 1));
    items.add(new Items("Whipped cream", 486, 1));
    //items.add(new Items("Whipped topping", 487, 1));
    items.add(new Items("White beans", 488, 1));
    items.add(new Items("White rice", 489, 1));
    items.add(new Items("White vinegar", 490, 1));
    items.add(new Items("Wild rice", 491, 1));
    //items.add(new Items("Wipes", 492, 1));
    items.add(new Items("Worcestershire Sauce", 493, 1));
    items.add(new Items("Yeast", 494, 1));
    items.add(new Items("Yellow onions", 495, 1));
    items.add(new Items("Yogurt", 496, 1));
    items.add(new Items("Zucchini", 497, 1));

        if (items2.size() > 0){
            for (int i = 0; i < items2.size(); i++)
            {
                items.add(new Items(items2.get(i),0,1 ));
            }}


        return items;
    }

/*    public void putInList()
    {
        theList.put("null", 0);
        theList.put("Almond butter", 1);
        theList.put("Almond milk", 2);
        theList.put("Almonds", 3);
        //theList.put("Almonds", 4);
        theList.put("Aluminum foil", 5);
        theList.put("Amaranth", 6);
        theList.put("Anise", 7);
        theList.put("Antacid", 8);
        theList.put("Antibiotic", 9);
        theList.put("Deodorant", 10);
        theList.put("Apple cider vinegar", 11);
        theList.put("Apple Juice", 12);
        theList.put("Apple vinegar", 13);
        theList.put("Apples", 14);
        theList.put("Applesauce", 15);
        theList.put("Apricots", 16);
        theList.put("Artichokes", 17);
        theList.put("Arugula", 18);
        theList.put("Asparagus", 19);
        theList.put("Aspirin", 20);
        //theList.put("Automotive Parts", 21);
        theList.put("Avocado", 22);
        theList.put("Baby Carrots", 23);
        theList.put("Baby food", 24);
        theList.put("Baby wash", 25);
        theList.put("Bagels", 26);
        theList.put("Baguette", 27);
        theList.put("Baked beans", 28);
        theList.put("Baking powder", 29);
        theList.put("Baking Soda", 30);
        theList.put("Balsamic vinegar", 31);
        theList.put("Bamboo shoots", 32);
        theList.put("Bananas", 33);
        //theList.put("Band-aids", 34);
        theList.put("Barley", 35);
        theList.put("Basil", 36);
        theList.put("Bathroom cleaner", 37);
        //theList.put("Batteries", 38);
        theList.put("Bay leaf", 39);
        theList.put("BBQ Sauce", 40);
        theList.put("Beef", 41);
        theList.put("Beets", 42);
        theList.put("Bell peppers", 43);
        theList.put("Berries", 44);
        theList.put("Black beans", 45);
        theList.put("Black pepper", 46);
        theList.put("Blackberries", 47);
        theList.put("Black-eyed peas", 48);
        theList.put("Bleach", 49);
        theList.put("Bleu cheese", 50);
        theList.put("Blood oranges", 51);
        theList.put("Blueberries", 52);
        theList.put("Bok choy", 53);
        theList.put("Bouillon cubes", 54);
        theList.put("Brazil nuts", 55);
        theList.put("Bread", 56);
        theList.put("Bread crumbs", 57);
        theList.put("Breakfast food", 58);
        theList.put("Broccoli", 59);
        //theList.put("Broccoli", 60);
        theList.put("Brown rice", 61);
        theList.put("Brownies", 62);
        theList.put("Brussels sprouts", 63);
        theList.put("Buckwheat", 64);
        theList.put("Bulgar", 65);
        theList.put("Buns / Rolls", 66);
        theList.put("Burger night", 67);
        theList.put("Burritos", 68);
        theList.put("Butter", 69);
        theList.put("Cabbage", 70);
        theList.put("Cake", 71);
        theList.put("Cake icing", 72);
        theList.put("Cake Mix", 73);
        theList.put("Candy", 74);
        theList.put("Cantaloupe", 75);
        theList.put("Carrots", 76);
        theList.put("Cashews", 77);
        //theList.put("Cashews", 78);
        theList.put("Cassava", 79);
        theList.put("Cat food", 80);
        theList.put("Cat litter", 81);
        theList.put("Cat Treats", 82);
        theList.put("Catfish", 83);
        theList.put("Cauliflower", 84);
        theList.put("Cayenne pepper", 85);
        theList.put("Celery", 86);
        theList.put("Celery seed", 87);
        theList.put("Cereal", 88);
        theList.put("Cereal bars", 89);
        theList.put("Chai", 90);
        theList.put("Charcoal", 91);
        theList.put("Propane", 92);
        theList.put("Chard", 93);
        //theList.put("Cheddar", 94);
        theList.put("Cheddar cheese", 95);
        *//*theList.put("Cherries", 96);
        theList.put("Chestnuts", 97);
        theList.put("Chicken", 98);
        theList.put("Chickpeas", 99);
        theList.put("Chili", 100);
        theList.put("Chili night", 101);
        theList.put("Chili Pepper", 102);
        theList.put("Chili powder", 103);
        theList.put("Chip Dip", 104);
        theList.put("Chives", 105);
        theList.put("Chocolate chips / Cocoa", 106);
        theList.put("Cilantro", 107);
        theList.put("Cinnamon", 108);
        theList.put("Cling Wrap", 109);
        theList.put("Clove", 110);
        theList.put("Club soda / Tonic", 111);
        theList.put("Coca Cola", 112);
        theList.put("Coconuts", 113);
        theList.put("Coffee", 114);
        theList.put("Coffee / Filters", 115);
        theList.put("Cold / Flu / Sinus", 116);
        theList.put("Collard greens", 117);
        theList.put("Compress", 118);
        theList.put("Conditioner", 119);
        theList.put("Cookies", 120);
        theList.put("Cookies", 121);
        theList.put("Coriander", 122);
        theList.put("Corn", 123);
        theList.put("Corn chips", 124);
        theList.put("Cornmeal", 125);
        theList.put("Cosmetics", 126);
        theList.put("Cottage cheese", 127);
        theList.put("Cotton swabs / Balls", 128);
        theList.put("Couscous", 129);
        theList.put("Crab", 130);
        theList.put("Crackers", 131);
        theList.put("Cranberries", 132);
        theList.put("Cream / Soy creamer", 133);
        theList.put("Cream cheese", 134);
        theList.put("Crisp head lettuce", 135);
        theList.put("Croissants", 136);
        theList.put("Cucumbers", 137);
        theList.put("Cumin", 138);
        theList.put("Cups", 139);
        theList.put("Cutlery", 140);
        theList.put("Daikon", 141);
        theList.put("Dates", 142);
        theList.put("Detergent", 143);
        theList.put("Diapers", 144);
        theList.put("Dill", 145);
        theList.put("Dishwasher soap", 146);
        theList.put("Dog food", 147);
        theList.put("Dog Treats", 148);
        theList.put("Donuts", 149);
        theList.put("Dried fruit", 150);
        theList.put("Earl Grey Tea", 151);
        theList.put("Edamame", 152);
        theList.put("Egg substitute", 153);
        theList.put("Egg whites", 154);
        theList.put("Eggplant", 155);
        theList.put("Eggs", 156);
        theList.put("Electrolyte water", 157);
        theList.put("Endive", 158);
        theList.put("English Muffins", 159);
        theList.put("Facial cleanser", 160);
        theList.put("Facial tissue", 161);
        theList.put("Fake eggs", 162);
        theList.put("Fanta Lemon", 163);
        theList.put("Fanta Orange", 164);
        theList.put("Fava beans", 165);
        theList.put("Feminine products", 166);
        theList.put("Fennel", 167);
        theList.put("Feta cheese", 168);
        theList.put("Figs", 169);
        theList.put("Fish Sticks", 170);
        theList.put("Flax", 171);
        theList.put("Flea treatment", 172);
        theList.put("Floss", 173);
        theList.put("Flour", 174);
        theList.put("Flowers", 175);
        theList.put("Formula", 176);
        theList.put("Free-range eggs", 177);
        theList.put("Freezer bags", 178);
        theList.put("French Fries", 179);
        theList.put("Fresh bread", 180);
        theList.put("Frozen Breakfast", 181);
        theList.put("Frozen Vegetables", 182);
        theList.put("Fruit", 183);
        theList.put("Fruit juice", 184);
        theList.put("Gala Apples", 185);
        theList.put("Garbage bags", 186);
        theList.put("Garlic", 187);
        theList.put("Ginger", 188);
        theList.put("Glasses", 189);
        theList.put("Goat cheese", 190);
        theList.put("Golden Apples", 191);
        theList.put("Granola bars", 192);
        theList.put("Granola bars / Mix", 193);
        theList.put("Grapefruit", 194);
        theList.put("Grapes", 195);
        theList.put("Gravy", 196);
        theList.put("Green bean", 197);
        theList.put("Green bell peppers", 198);
        theList.put("Greens", 199);
        theList.put("Greeting cards", 200);
        theList.put("Ground beef", 201);
        theList.put("Ground Turkey", 202);
        theList.put("Guava", 203);
        theList.put("Gum", 204);
        theList.put("Habanero chili", 205);
        theList.put("Hair gel / Spray", 206);
        theList.put("Half & half", 207);
        theList.put("Honey", 208);
        theList.put("Honeydew / Muskmelon", 209);
        theList.put("Hot dogs", 210);
        theList.put("Hot peppers", 211);
        theList.put("Hot Sauce", 212);
        theList.put("Hummus", 213);
        theList.put("Ice Cream", 214);
        theList.put("Insect repellent", 215);
        theList.put("Instant potatoes", 216);
        theList.put("Jalapeños", 217);
        theList.put("Jam", 218);
        theList.put("Jam", 219);
        theList.put("Jelly", 220);
        theList.put("Jicama", 221);
        theList.put("Juice", 222);
        theList.put("Juice Concentrate", 223);
        theList.put("Kale", 224);
        theList.put("Ketchup", 225);
        theList.put("Kidney beans", 226);
        theList.put("Kiwifruits", 227);
        theList.put("Kiwis", 228);
        theList.put("Kohlrabi", 229);
        theList.put("Kombucha", 230);
        theList.put("Kumquats", 231);
        theList.put("Lavender", 232);
        theList.put("Leeks", 233);
        theList.put("Lemon Juice", 234);
        theList.put("Lemongrass", 235);
        theList.put("Lemons", 236);
        theList.put("Lentils", 237);
        theList.put("Lettuce", 238);
        theList.put("Lima beans", 239);
        theList.put("Lime juice", 240);
        theList.put("Limes", 241);
        theList.put("Limes", 242);
        theList.put("Lip balm", 243);
        theList.put("Lobster", 244);
        theList.put("Lotion", 245);
        theList.put("Lotus", 246);
        theList.put("Lunchmeat", 247);
        theList.put("Lychee", 248);
        theList.put("Mac & Cheese", 249);
        theList.put("Macadamia", 250);
        theList.put("Makeup", 251);
        theList.put("Mandarin oranges", 252);
        theList.put("Mango", 253);
        theList.put("Mangosteen", 254);
        theList.put("Margarine", 255);
        theList.put("Marjoram", 256);
        theList.put("Mashed Potatoes", 257);
        theList.put("Mayonnaise", 258);
        theList.put("Melon", 259);
        theList.put("Milk", 260);
        theList.put("Milk powder", 261);
        theList.put("Millet", 262);
        theList.put("Mint", 263);
        theList.put("Moisturizing lotion", 264);
        theList.put("Mop head", 265);
        theList.put("Mouthwash", 266);
        theList.put("Mozzarella", 267);
        theList.put("Mozzarella cheese", 268);
        theList.put("Mung beans", 269);
        theList.put("Mushrooms", 270);
        theList.put("Mussels", 271);
        theList.put("Mustard", 272);
        theList.put("Mustard", 273);
        theList.put("Napkins", 274);
        theList.put("Nappies", 275);
        theList.put("Navy beans", 276);
        theList.put("Nectarines", 277);
        theList.put("Non-stick spray", 278);
        theList.put("Nopales", 279);
        theList.put("Nutmeg", 280);
        theList.put("Nutritional yeast", 281);
        theList.put("Nuts", 282);
        theList.put("Oatmeal", 283);
        theList.put("Okra", 284);
        theList.put("Olive Oil", 285);
        theList.put("Olives", 286);
        theList.put("Onions", 287);
        theList.put("Orange Juice", 288);
        theList.put("Orange Juice", 289);
        theList.put("Oranges", 290);
        theList.put("Oregano", 291);
        theList.put("Oysters", 292);
        theList.put("Pain reliever", 293);
        theList.put("Pancake mix", 294);
        theList.put("Papaya", 295);
        theList.put("Paper towels", 296);
        theList.put("Paprika", 297);
        theList.put("Parmesan", 298);
        theList.put("Parmesan cheese", 299);
        theList.put("Parsley", 300);
        theList.put("Parsnips", 301);
        theList.put("Passionfruit", 302);
        theList.put("Pasta", 303);
        theList.put("Pasta Sauce", 304);
        theList.put("Pastries", 305);
        theList.put("Peach Juice", 306);
        theList.put("Peaches", 307);
        theList.put("Peanut butter", 308);
        theList.put("Peanuts", 309);
        theList.put("Pears", 310);
        theList.put("Peas", 311);
        theList.put("Pecans", 312);
        theList.put("Pens / Pencils", 313);
        theList.put("Peppermint", 314);
        theList.put("Peppers", 315);
        theList.put("Pet shampoo", 316);
        theList.put("Pickles", 317);
        theList.put("Pie!", 318);
        theList.put("Pine nuts", 319);
        theList.put("Pineapple", 320);
        theList.put("Pineapple Juice", 321);
        theList.put("Pinto beans", 322);
        theList.put("Pistachios", 323);
        theList.put("Pita bread", 324);
        theList.put("Pitas", 325);
        theList.put("Pizza", 326);
        theList.put("Pizza", 327);
        theList.put("Pizza Rolls", 328);
        theList.put("Plantains", 329);
        theList.put("Plastic wrap", 330);
        theList.put("Plates", 331);
        theList.put("Plums", 332);
        theList.put("Pomegranates", 333);
        theList.put("Popcorn", 334);
        theList.put("Poppy seed", 335);
        theList.put("Popsicles", 336);
        theList.put("Postage stamps", 337);
        theList.put("Potato chips", 338);
        theList.put("Potatoes", 339);
        theList.put("Prepared meals", 340);
        theList.put("Prescription pick-up", 341);
        theList.put("Preserves", 342);
        theList.put("Pretzels", 343);
        theList.put("Printer paper", 344);
        theList.put("Provolone cheese", 345);
        theList.put("Prunes", 346);
        theList.put("Puff pastry", 347);
        theList.put("Pumpkin", 348);
        theList.put("Quail Eggs", 349);
        theList.put("Quince", 350);
        theList.put("Quinoa", 351);
        theList.put("Radicchio", 352);
        theList.put("Radishes", 353);
        theList.put("Raisins", 354);
        theList.put("Ranch", 355);
        theList.put("Random impulse buy!", 356);
        theList.put("Raspberries", 357);
        theList.put("Raspberry", 358);
        theList.put("Razors", 359);
        theList.put("Ready-bake breads", 360);
        theList.put("Red beans", 361);
        theList.put("Red bell peppers", 362);
        theList.put("Red Cabbages", 363);
        theList.put("Red onions", 364);
        theList.put("Red Pepper", 365);
        theList.put("Red pepper", 366);
        theList.put("Red wine vinegar", 367);
        theList.put("Relish", 368);
        theList.put("Rhubarb", 369);
        theList.put("Rice", 370);
        theList.put("Rice", 371);
        theList.put("Rice milk", 372);
        theList.put("Rice vinegar", 373);
        theList.put("Ricotta", 374);
        theList.put("Ricotta cheese", 375);
        theList.put("Romaine lettuce", 376);
        theList.put("Rosemary", 377);
        theList.put("Saffron", 378);
        theList.put("Salad Dressing", 379);
        theList.put("Salmon", 380);
        theList.put("Salsa", 381);
        theList.put("Salt", 382);
        theList.put("Sandwich bags", 383);
        theList.put("Sandwich cheese slices", 384);
        theList.put("Sandwich slices", 385);
        theList.put("Seeds", 386);
        theList.put("Sesame oil", 387);
        theList.put("Shallots", 388);
        theList.put("Shampoo", 389);
        theList.put("Shaving cream", 390);
        theList.put("Shortening", 391);
        theList.put("Shrimp", 392);
        theList.put("Sliced bread", 393);
        theList.put("Sliced bread", 394);
        theList.put("Sliced bread", 395);
        theList.put("Soap", 396);
        theList.put("Soda pop", 397);
        theList.put("Sorbet", 398);
        theList.put("Sorbet", 399);
        theList.put("Sorghum", 400);
        theList.put("Soups", 401);
        theList.put("Sour cream", 402);
        theList.put("Soy butter", 403);
        theList.put("Soy I.C.", 404);
        theList.put("Soy milk", 405);
        theList.put("Soy Sauce", 406);
        theList.put("Soy yogurt", 407);
        theList.put("Spaghetti night", 408);
        theList.put("Spice mix", 409);
        theList.put("Spices", 410);
        theList.put("Spinach", 411);
        theList.put("Split peas", 412);
        theList.put("Sponges / Scrubbers", 413);
        theList.put("Sports drink", 414);
        theList.put("Sprite", 415);
        theList.put("Sprouts", 416);
        theList.put("Squash", 417);
        theList.put("Steak", 418);
        theList.put("Steak Sauce", 419);
        theList.put("Stevia", 420);
        theList.put("Stir fry sauce", 421);
        theList.put("Strawberries", 422);
        theList.put("Sugar", 423);
        theList.put("Sugar substitute", 424);
        theList.put("Sunblock", 425);
        theList.put("Sunflower", 426);
        theList.put("Supplements", 427);
        theList.put("Sweet corn", 428);
        theList.put("Sweet potatoes", 429);
        theList.put("Swiss", 430);
        theList.put("Swiss cheese", 431);
        theList.put("Syrup", 432);
        theList.put("Taco night", 433);
        theList.put("Tahini", 434);
        theList.put("Take-out deli food", 435);
        theList.put("Tangerines", 436);
        theList.put("Taro", 437);
        theList.put("Tater tots", 438);
        theList.put("Tea", 439);
        theList.put("Tempeh", 440);
        theList.put("Tilapia", 441);
        theList.put("Tinned meats", 442);
        theList.put("Tofu", 443);
        theList.put("Toilet paper", 444);
        theList.put("Tomatillo", 445);
        theList.put("Tomato sauce", 446);
        theList.put("Tomatoes", 447);
        theList.put("Toothpaste", 448);
        theList.put("Tortillas", 449);
        theList.put("Tortillas", 450);
        theList.put("Trail mix", 451);
        theList.put("Tuna", 452);
        theList.put("Tuna / Chicken", 453);
        theList.put("Turkey", 454);
        theList.put("Turkey", 455);
        theList.put("Turmeric", 456);
        theList.put("Turnips", 457);
        theList.put("Turnips / Parsnips", 458);
        theList.put("TV Dinner", 459);
        theList.put("TV dinners", 460);
        theList.put("TVP", 461);
        theList.put("Vacuum bags", 462);
        theList.put("Vanilla extract", 463);
        theList.put("Veg. Worcestershire", 464);
        theList.put("Vegetable oil", 465);
        theList.put("Vegetable shortening", 466);
        theList.put("Vegetables", 467);
        theList.put("Veggie breakfasts", 468);
        theList.put("Veggie Burger", 469);
        theList.put("Veggie burgers", 470);
        theList.put("Veggie burritos", 471);
        theList.put("Veggie dogs", 472);
        theList.put("Veggie pizzas", 473);
        theList.put("Veggies", 474);
        theList.put("Vinegar", 475);
        theList.put("Vitamins", 476);
        theList.put("Waffle mix", 477);
        theList.put("Walnut", 478);
        theList.put("Walnuts", 479);
        theList.put("Water Bottles", 480);
        theList.put("Water chestnuts", 481);
        theList.put("Watercress", 482);
        theList.put("Watermelon", 483);
        theList.put("Wax paper", 484);
        theList.put("Wheat gluten", 485);
        theList.put("Whipped cream", 486);
        theList.put("Whipped topping", 487);
        theList.put("White beans", 488);
        theList.put("White rice", 489);
        theList.put("White vinegar", 490);
        theList.put("Wild rice", 491);
        theList.put("Wipes", 492);
        theList.put("Worcestershire Sauce", 493);
        theList.put("Yeast", 494);
        theList.put("Yellow onions", 495);
        theList.put("Yogurt", 496);
        theList.put("Zucchini", 497);*//*


    }

    public void arraylistInitValues(){
        names.add("Asparagus");
        names.add("Broccoli");
        names.add("Carrots");
        names.add("Cauliflower");
        names.add("Celery");
        names.add("Corn");
        names.add("Cucumbers");
        names.add("Lettuce");
        names.add("Mushrooms");
        names.add("Onions");
        names.add("Peppers");
        names.add("Potatoes");
        names.add("Spinach");
        names.add("Squash");
        names.add("Zucchini");
        names.add("Tomatoes");
        names.add("Apples");
        names.add("Avocados");
        names.add("Bananas");
        names.add("Berries");
        names.add("Cherries");
        names.add("Grapefruit");
        names.add("Grapes");
        names.add("Kiwis");
        names.add("Lemons");
        names.add("Limes");
        names.add("Melon");
        names.add("Blueberries");
        names.add("Raspberry");
        names.add("Oranges");
        names.add("Peaches");
        names.add("Nectarines");
        names.add("Pears");
        names.add("Plums");
        names.add("Watermelon");
        names.add("Kale");
        names.add("Bagels");
        names.add("Chip Dip");
        names.add("English Muffins");
        names.add("Eggs");
        names.add("Orange Juice");
        names.add("Hummus");
        names.add("Bread");
        names.add("Baguette");
        names.add("Tofu");
        names.add("Tortillas");
        names.add("Frozen Breakfast");
        names.add("Burrito");
        names.add("Fish Sticks");
        names.add("Ice Cream");
        names.add("Juice Concentrate");
        names.add("Pizza");
        names.add("Popsicles");
        names.add("Fries");
        names.add("TV Dinner");
        names.add("Frozen Vegetables");
        names.add("Veggie Burger");
        names.add("BBQ Sauce");
        names.add("Gravy");
        names.add("Honey");
        names.add("Hot Sauce");
        names.add("Jam");
        names.add("Ketchup");
        names.add("Mustard");
        names.add("Mayonnaise");
        names.add("Pasta Sauce");
        names.add("Relish");
        names.add("Salad Dressing");
        names.add("Salsa");
        names.add("Soy Sauce");
        names.add("Steak Sauce");
        names.add("Syrup");
        names.add("Worcestershire Sauce");
        names.add("Ranch");
        names.add("Cereal");
        names.add("Coffee");
        names.add("Mashed Potatoes");
        names.add("Lemon Juice");
        names.add("Mac & Cheese");
        names.add("Olive Oil");
        names.add("Arugula");
        names.add("Avocado");
        names.add("Bamboo shoots");
        names.add("Beets");
        names.add("Bell peppers");
        names.add("Bok choy");
        names.add("Brussels sprouts");
        names.add("Cabbage");
        names.add("Cassava");
        names.add("Chard");
        names.add("Collard greens");
        names.add("Crisphead lettuce");
        names.add("Cucumber");
        names.add("Daikon");
        names.add("Eggplant");
        names.add("Endive");
        names.add("Garlic");
        names.add("Ginger");
        names.add("Hot peppers");
        names.add("Jicama");
        names.add("Kohlrabi");
        names.add("Apricots");
        names.add("Blackberries");
        names.add("Cantelope");
        names.add("Cranberries");
        names.add("Dates / Figs");
        names.add("Guava");
        names.add("Honeydew / Muskmelon");
        names.add("Kumquats");
        names.add("Lychee");
        names.add("Mango");
        names.add("Mangosteen");
        names.add("Papaya");
        names.add("Pineapple");
        names.add("Plantains");
        names.add("Nopales");
        names.add("Okra");
        names.add("Peas");
        names.add("Radishes");
        names.add("Radicchio");
        names.add("Romaine lettuce");
        names.add("Shallots / Leeks");
        names.add("Sprouts");
        names.add("Sweet potatoes");
        names.add("Taro");
        names.add("Tomatillo");
        names.add("Turnips / Parsnips");
        names.add("Water chestnuts");
        names.add("Watercress");
        names.add("Almonds");
        names.add("Brazil nuts");
        names.add("Cashews");
        names.add("Chestnuts");
        names.add("Macadamia");
        names.add("Peanuts");
        names.add("Pecans");
        names.add("Pine nuts");
        names.add("Pistachios");
        names.add("Walnuts");
        names.add("Flax");
        names.add("Lotus");
        names.add("Pumpkin");
        names.add("Sunflower");
        names.add("Quince");
        names.add("Raspberries");
        names.add("Rhubarb");
        names.add("Strawberries");
        names.add("Black beans");
        names.add("Black-eyed peas");
        names.add("Chickpeas");
        names.add("Edamame");
        names.add("Fava beans");
        names.add("Kidney beans");
        names.add("Lentils");
        names.add("Lima beans");
        names.add("Mung beans");
        names.add("Navy beans");
        names.add("Pinto beans");
        names.add("Red beans");
        names.add("Split peas");
        names.add("White beans");
        names.add("Amaranth");
        names.add("Barley");
        names.add("Brown rice");
        names.add("Buckwheat");
        names.add("Bulgar");
        names.add("Cornmeal");
        names.add("Couscous");
        names.add("Millet");
        names.add("Oatmeal");
        names.add("Quinoa");
        names.add("Sorghum");
        names.add("Wheat gluten (Seitan)");
        names.add("White rice");
        names.add("Wild rice");
        names.add("Stir fry sauce");
        names.add("Tomato sauce");
        names.add("Veg. Worcestershire");
        names.add("Allspice");
        names.add("Anise");
        names.add("Bay leaf");
        names.add("Basil");
        names.add("Black pepper");
        names.add("Cayenne pepper");
        names.add("Celery seed");
        names.add("Chives");
        names.add("Chili powder");
        names.add("Cilantro");
        names.add("Cinnamon");
        names.add("Clove");
        names.add("Coriander");
        names.add("Cumin");
        names.add("Dill");
        names.add("Fennel");
        names.add("Lavender");
        names.add("Lemongrass");
        names.add("Marjoram");
        names.add("Nutmeg");
        names.add("Oregano");
        names.add("Paprika");
        names.add("Parsley");
        names.add("Peppermint");
        names.add("Poppy seed");
        names.add("Red pepper");
        names.add("Rosemary");
        names.add("Saffron");
        names.add("Club soda / Tonic");
        names.add("Electrolyte water");
        names.add("Juices");
        names.add("Kombucha");
        names.add("Liquor");
        names.add("Mixers");
        names.add("Soda pop");
        names.add("Sports drink");
        names.add("Almond butter");
        names.add("Almond milk");
        names.add("Bleu cheese");
        names.add("Butter / Soy butter");
        names.add("Cheddar");
        names.add("Cottage cheese");
        names.add("Cream cheese");
        names.add("Cream / Soy creamer");
        names.add("Margarine / Soy marg.");
        names.add("Milk / Soy milk");
        names.add("Mozzarella");
        names.add("Parmesan");
        names.add("Provolone");
        names.add("Bagels / Croissants");
        names.add("Buns / Rolls");
        names.add("Cake");
        names.add("Donuts / Pastries");
        names.add("Fresh / Sliced bread");
        names.add("Pie! Pie! Pie!");
        names.add("Pitas / Tortillas");
        names.add("Baking powder / Soda");
        names.add("Bread crumbs");
        names.add("Cake icing / Decorations");
        names.add("Cake / Brownie mix");
        names.add("Chocolate chips / Cocoa");
        names.add("Flour");
        names.add("Stevia");
        names.add("Sugar");
        names.add("Sugar substitute");
        names.add("Vegetable shortening");
        names.add("Yeast");
        names.add("Apple cider vinegar");
        names.add("Balsamic vinegar");
        names.add("Red wine vinegar");
        names.add("Rice vinegar");
        names.add("Sesame oil");
        names.add("Vegetable oil");
        names.add("White vinegar");
        names.add("Apple vinegar");
        names.add("Candy / Gum");
        names.add("Cookies");
        names.add("Crackers");
        names.add("Dried fruit / Trail mix");
        names.add("Granola / Cereal bars");
        names.add("Popcorn");
        names.add("Potato / Corn chips");
        names.add("Prunes / Raisins");
        names.add("Pretzels");
        names.add("Rice milk");
        names.add("Ricotta");
        names.add("Sandwich slices");
        names.add("Sour cream");
        names.add("Swiss");
        names.add("Whipped topping");
        names.add("Yogurt / Soy yogurt");
        names.add("Fries / Tater tots");
        names.add("Ice cream / Soy I.C.");
        names.add("Phyllo / Puff pastry");
        names.add("Prepared meals");
        names.add("Sorbet");
        names.add("Vegetables");
        names.add("Veggie breakfasts");
        names.add("Veggie burgers");
        names.add("Veggie burritos");
        names.add("Veggie pizzas");
        names.add("Chai");
        names.add("Coffee / Filters");
        names.add("Free-range eggs");
        names.add("Egg substitute");
        names.add("Lemon / Lime juice");
        names.add("Nutritional yeast");
        names.add("Pancake / Waffle mix");
        names.add("Pasta");
        names.add("Pickles");
        names.add("Tahini");
        names.add("Tea");
        names.add("Tempeh");
        names.add("TVP");
        names.add("Veggie dogs");
        names.add("AsparagusBroccoli");
        names.add("Lettuce / Greens");
        names.add("Lemons / Limes");
        names.add("Passionfruit");
        names.add("Eggs / Fake eggs");
        names.add("Fruit juice");
        names.add("Ready-bake breads");
        names.add("Breakfasts");
        names.add("Burritos");
        names.add("Ice cream / Sorbet");
        names.add("Pizza / Pizza Rolls");
        names.add("TV dinners");
        names.add("Jam / Jelly / Preserves");
        names.add("Ketchup / Mustard");
        names.add("Bouillon cubes");
        names.add("Instant potatoes");
        names.add("Peanut butter");
        names.add("Rice");
        names.add("Vinegar");
        names.add("Applesauce");
        names.add("Baked beans");
        names.add("Chili");
        names.add("Fruit");
        names.add("Olives");
        names.add("Tinned meats");
        names.add("Tuna / Chicken");
        names.add("Soups");
        names.add("Veggies");
        names.add("Mint");
        names.add("Salt");
        names.add("Spice mix");
        names.add("Vanilla extract");
        names.add("Butter / Margarine");
        names.add("Half & half");
        names.add("Milk");
        names.add("Whipped cream");
        names.add("Yogurt");
        names.add("Cheddar cheese");
        names.add("Feta cheese");
        names.add("Goat cheese");
        names.add("Mozzarella cheese");
        names.add("Parmesan cheese");
        names.add("Provolone cheese");
        names.add("Ricotta cheese");
        names.add("Sandwich cheese slices");
        names.add("Swiss cheese");
        names.add("Beef");
        names.add("Chicken");
        names.add("Ground beef / Turkey");
        names.add("Hot dogs");
        names.add("Lunchmeat");
        names.add("Turkey");
        names.add("Catfish");
        names.add("Crab");
        names.add("Lobster");
        names.add("Mussels");
        names.add("Oysters");
        names.add("Salmon");
        names.add("Shrimp");
        names.add("Tilapia");
        names.add("Tuna");
        names.add("Coca Cola");
        names.add("Champagne");
        names.add("Gin");
        names.add("Juice");
        names.add("Sprite");
        names.add("Fanta");
        names.add("Water Bottles");
        names.add("Cake / Cookies");
        names.add("Fresh bread");
        names.add("Sliced bread");
        names.add("Pie");
        names.add("Pita bread");
        names.add("Shortening");
        names.add("Dried fruit");
        names.add("Granola bars / Mix");
        names.add("Nuts / Seeds");
        names.add("Burger night");
        names.add("Chili night");
        names.add("Pizza night");
        names.add("Spaghetti night");
        names.add("Taco night");
        names.add("Take-out deli food");
        names.add("Baby food");
        names.add("Formula");
        names.add("Lotion");
        names.add("Baby wash");
        names.add("Wipes");
        names.add("Nappies");
        names.add("Milk powder");
        names.add("Cat food / Treats");
        names.add("Cat litter");
        names.add("Dog food / Treats");
        names.add("Flea treatment");
        names.add("Pet shampoo");
        names.add("Antiperspirant / Deodorant");
        names.add("Bath soap / Hand soap");
        names.add("Cosmetics");
        names.add("Cotton swabs / Balls");
        names.add("Facial cleanser");
        names.add("Facial tissue");
        names.add("Feminine products");
        names.add("Floss");
        names.add("Hair gel / Spray");
        names.add("Lip balm");
        names.add("Moisturizing lotion");
        names.add("Mouthwash");
        names.add("Razors / Shaving cream");
        names.add("Shampoo / Conditioner");
        names.add("Sunblock");
        names.add("Toilet paper");
        names.add("Toothpaste");
        names.add("Vitamins / Supplements");
        names.add("Allergy");
        names.add("Antibiotic");
        names.add("Antidiarrheal");
        names.add("Aspirin");
        names.add("Antacid");
        names.add("Band-aids / Medical");
        names.add("Cold / Flu / Sinus");
        names.add("Pain reliever");
        names.add("Prescription pick-up");
        names.add("Aluminum foil");
        names.add("Napkins");
        names.add("Non-stick spray");
        names.add("Paper towels");
        names.add("Plastic wrap");
        names.add("Sandwich / Freezer bags");
        names.add("Wax paper");
        names.add("Air freshener");
        names.add("Bathroom cleaner");
        names.add("Bleach / Detergent");
        names.add("Dish / Dishwasher soap");
        names.add("Garbage bags");
        names.add("Glass cleaner");
        names.add("Mop head / Vacuum bags");
        names.add("Sponges / Scrubbers");
        names.add("Notepad / Envelopes");
        names.add("Glue / Tape");
        names.add("Printer paper");
        names.add("Pens / Pencils");
        names.add("Postage stamps");
        names.add("Automotive");
        names.add("Batteries");
        names.add("Charcoal / Propane");
        names.add("Flowers / Greeting card");
        names.add("Insect repellent");
        names.add("Light bulbs");
        names.add("Newspaper / Magazine");
        names.add("Random impulse buy");




    }*/
}
